### ISSUE TITLE
Not working when MQTT server does not require credentials

### ISSUE THREAD

**Issue by tricoos** [monster1025/yeelight-mqtt#5]
ARM (Raspberry Pi) - credentials in YAML file exist but are empty as the server does not require credentials:
```
yeelight    | INFO:__main__:Loading config file...
yeelight    | /app/yamlparser.py:9: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
yeelight    |   yaml_data = yaml.load(stram)
yeelight    | INFO:__main__:Init mqtt client.
yeelight    | Traceback (most recent call last):
yeelight    |   File "/app/main.py", line 97, in <module>
yeelight    |     client.connect()
yeelight    |   File "/app/mqtt.py", line 44, in connect
yeelight    |     _LOGGER.info("Connecting to MQTT server " + self.server + ":" + str(self.port) + " with username (" + self.username + ":" + self.password + ")")
yeelight    | TypeError: can only concatenate str (not "NoneType") to str
```

Probably the YAML parser does not return empty attributes and you're trying to concatenate NULL in the log message?

**Comment by tricoos** [comment]
Update: it works so far when the log output of the credentials is removed. In any way logging credentials should never be done for security reasons.
